In [1]:
import numpy as np
import pandas as pd

In [57]:
cf=pd.read_csv("Catfish_Trout.csv")

In [58]:
cf.head()

SOURCE_ID COMMODITY_DESC  GEOGRAPHY_CODE            GEOGRAPHY_DESC  \
0        101        Catfish          9000.0  United States of America   
1        101        Catfish          9000.0  United States of America   
2        101        Catfish          9000.0  United States of America   
3        101        Catfish          9000.0  United States of America   
4        101        Catfish          9000.0  United States of America   

  ATTRIBUTE_DESC    UNIT_DESC  YEAR_ID  TIMEPERIOD_ID  AMOUNT  
0     Farm Price  Cents/Pound     1986              1    70.0  
1     Farm Price  Cents/Pound     1986              2    70.0  
2     Farm Price  Cents/Pound     1986              3    72.0  
3     Farm Price  Cents/Pound     1986              4    74.0  
4     Farm Price  Cents/Pound     1986              5    72.0

In [59]:
cf['TIMEPERIOD_ID'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 17], dtype=int64)

In [60]:
cf=cf[cf['TIMEPERIOD_ID']!=17]

In [61]:
cf['TIMEPERIOD_ID'].unique()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int64)

In [81]:
cf['DATE']=cf['YEAR_ID'].astype(str)+"-"+cf['TIMEPERIOD_ID'].astype(str)+"-"+str(1)

In [82]:
cf.head()

SOURCE_ID COMMODITY_DESC  GEOGRAPHY_CODE            GEOGRAPHY_DESC  \
0        101        Catfish          9000.0  United States of America   
1        101        Catfish          9000.0  United States of America   
2        101        Catfish          9000.0  United States of America   
3        101        Catfish          9000.0  United States of America   
4        101        Catfish          9000.0  United States of America   

  ATTRIBUTE_DESC    UNIT_DESC  YEAR_ID  TIMEPERIOD_ID  AMOUNT      DATE  
0     Farm Price  Cents/Pound     1986              1    70.0  1986-1-1  
1     Farm Price  Cents/Pound     1986              2    70.0  1986-2-1  
2     Farm Price  Cents/Pound     1986              3    72.0  1986-3-1  
3     Farm Price  Cents/Pound     1986              4    74.0  1986-4-1  
4     Farm Price  Cents/Pound     1986              5    72.0  1986-5-1

In [83]:
unit_names=cf['UNIT_DESC'].unique()

In [95]:
cf1=cf[cf['UNIT_DESC']==unit_names[2]]

In [96]:
df =cf1.pivot_table(index='DATE', columns=['COMMODITY_DESC','ATTRIBUTE_DESC'], values='AMOUNT')

In [97]:
df2=df.dropna(axis=1)

In [98]:
df2.shape

(326, 12)

In [99]:
df2.to_csv('catfish_wide_unit3.csv')

In [64]:
df =cf.pivot_table(index='DATE', columns=['COMMODITY_DESC','ATTRIBUTE_DESC','UNIT_DESC'], values='AMOUNT')

In [65]:
df.head()

COMMODITY_DESC     Catfish                                        \
ATTRIBUTE_DESC  Farm Price Farm Sales to Processors Imports, QTY   
UNIT_DESC      Cents/Pound             1,000 Pounds 1,000 Pounds   
DATE                                                               
1986-1                70.0                  19761.0        383.0   
1986-10               62.0                  20453.0        800.0   
1986-11               61.0                  17107.0       1142.0   
1986-12               61.0                  15812.0        199.0   
1986-2                70.0                  19083.0        947.0   

COMMODITY_DESC                                        \
ATTRIBUTE_DESC Processor Inventories Processor Price   
UNIT_DESC               1,000 Pounds     Cents/Pound   
DATE                                                   
1986-1                        5103.0           201.0   
1986-10                       4021.0           185.5   
1986-11                       4223.0           186.4   
1986-12                       4147.0           185.2   
1986-2                        5361.0           199.0   

COMMODITY_DESC                                 Catfish-Fresh Filleted Fish  \
ATTRIBUTE_DESC Processor Sales, All categories       Processor Inventories   
UNIT_DESC                         1,000 Pounds                1,000 Pounds   
DATE                                                                         
1986-1                                  9034.0                       143.0   
1986-10                                10649.0                       104.0   
1986-11                                 8917.0                       108.0   
1986-12                                 8196.0                       124.0   
1986-2                                  9596.0                        94.0   

COMMODITY_DESC                                 Catfish-Fresh Fish Total  ...  \
ATTRIBUTE_DESC Processor Price Processor Sales    Processor Inventories  ...   
UNIT_DESC              $/Pound    1,000 Pounds             1,000 Pounds  ...   
DATE                                                                     ...   
1986-1                    2.73          1091.0                    381.0  ...   
1986-10                   2.53          1438.0                    317.0  ...   
1986-11                   2.52          1086.0                    364.0  ...   
1986-12                   2.50          1036.0                    332.0  ...   
1986-2                    2.66          1222.0                    279.0  ...   

COMMODITY_DESC Catfish-Frozen Other Fish, Other  \
ATTRIBUTE_DESC                  Processor Sales   
UNIT_DESC                          1,000 Pounds   
DATE                                              
1986-1                                      NaN   
1986-10                                     NaN   
1986-11                                     NaN   
1986-12                                     NaN   
1986-2                                      NaN   

COMMODITY_DESC Catfish-Frozen Other Fish, Steaks                  \
ATTRIBUTE_DESC             Processor Inventories Processor Price   
UNIT_DESC                           1,000 Pounds         $/Pound   
DATE                                                               
1986-1                                       NaN             NaN   
1986-10                                      NaN             NaN   
1986-11                                      NaN             NaN   
1986-12                                      NaN             NaN   
1986-2                                       NaN             NaN   

COMMODITY_DESC                 Catfish-Frozen Whole Fish                  \
ATTRIBUTE_DESC Processor Sales     Processor Inventories Processor Price   
UNIT_DESC         1,000 Pounds              1,000 Pounds         $/Pound   
DATE                                                                       
1986-1                     NaN                    1684.0            1.66   
1986-

In [66]:
df.shape

(326, 63)

In [67]:
df=df.dropna(axis=1, how='all')

In [68]:
df.shape

(326, 63)

In [69]:
df.to_csv("castfish_wide.csv")

In [71]:
df1=df.dropna(axis=1)

In [72]:
df1.shape

(326, 37)

In [73]:
df1.to_csv("castfish_wide1.csv")

In [74]:
df1.head()

COMMODITY_DESC     Catfish                                                 \
ATTRIBUTE_DESC  Farm Price Farm Sales to Processors Processor Inventories   
UNIT_DESC      Cents/Pound             1,000 Pounds          1,000 Pounds   
DATE                                                                        
1986-1                70.0                  19761.0                5103.0   
1986-10               62.0                  20453.0                4021.0   
1986-11               61.0                  17107.0                4223.0   
1986-12               61.0                  15812.0                4147.0   
1986-2                70.0                  19083.0                5361.0   

COMMODITY_DESC                                                  \
ATTRIBUTE_DESC Processor Price Processor Sales, All categories   
UNIT_DESC          Cents/Pound                    1,000 Pounds   
DATE                                                             
1986-1                   201.0                          9034.0   
1986-10                  185.5                         10649.0   
1986-11                  186.4                          8917.0   
1986-12                  185.2                          8196.0   
1986-2                   199.0                          9596.0   

COMMODITY_DESC Catfish-Fresh Filleted Fish                                  \
ATTRIBUTE_DESC       Processor Inventories Processor Price Processor Sales   
UNIT_DESC                     1,000 Pounds         $/Pound    1,000 Pounds   
DATE                                                                         
1986-1                               143.0            2.73          1091.0   
1986-10                              104.0            2.53          1438.0   
1986-11                              108.0            2.52          1086.0   
1986-12                              124.0            2.50          1036.0   
1986-2                                94.0            2.66          1222.0   

COMMODITY_DESC Catfish-Fresh Fish Total                  ...  \
ATTRIBUTE_DESC    Processor Inventories Processor Price  ...   
UNIT_DESC                  1,000 Pounds         $/Pound  ...   
DATE                                                     ...   
1986-1                            381.0            1.86  ...   
1986-10                           317.0            1.72  ...   
1986-11                           364.0            1.69  ...   
1986-12                           332.0            1.68  ...   
1986-2                            279.0            1.83  ...   

COMMODITY_DESC Catfish-Frozen Filleted Fish Catfish-Frozen Fish Total  \
ATTRIBUTE_DESC              Processor Sales     Processor Inventories   
UNIT_DESC                      1,000 Pounds              1,000 Pounds   
DATE                                                                    
1986-1                               2212.0                    4722.0   
1986-10                              2386.0                    3704.0   
1986-11                              2272.0                    3859.0   
1986-12                              1951.0                    3815.0   
1986-2                               2245.0                    5082.0   

COMMODITY_DESC                                 Catfish-Frozen Other Fish  \
ATTRIBUTE_DESC Processor Price Processor Sales     Processor Inventories   
UNIT_DESC              $/Pound    1,000 Pounds              1,000 Pounds   
DATE                                                                       
1986-1                    2.15          4670.0                     963.0   
1986-10                   1.99          5315.0                     749.0   
1986-11                   2.04          4433.0                     879.0   
1986-12                   2.03          4023.0                     771.0   
1986-2                    2.17          4513.0                     638.0   

COMMODITY_DESC                                 Catfish-Frozen Whole Fish  \
ATTRIBUTE_DE

In [77]:
df1.columns[0]

('Catfish', 'Farm Price', 'Cents/Pound')

In [78]:
cf['UNIT_DESC'].unique()

array(['Cents/Pound', '1,000 Pounds', '$/Pound'], dtype=object)

In [80]:
df2=df1[df1.columns[:,2]=='Cents/Pound']

IndexError: too many indices for array

In [33]:
list_1=cf['COMMODITY_DESC'].unique()

In [34]:
list_2=cf['UNIT_DESC'].unique()

In [35]:
list_3=cf['ATTRIBUTE_DESC'].unique()

In [41]:
df=cf.groupby(['COMMODITY_DESC','ATTRIBUTE_DESC','UNIT_DESC']).AMOUNT.unstack()

AttributeError: 'SeriesGroupBy' object has no attribute 'unstack'

In [6]:
cf_filter=cf[cf['COMMODITY_DESC']=='Catfish']

In [7]:
cf_filter.head()

SOURCE_ID COMMODITY_DESC  GEOGRAPHY_CODE            GEOGRAPHY_DESC  \
0        101        Catfish          9000.0  United States of America   
1        101        Catfish          9000.0  United States of America   
2        101        Catfish          9000.0  United States of America   
3        101        Catfish          9000.0  United States of America   
4        101        Catfish          9000.0  United States of America   

  ATTRIBUTE_DESC    UNIT_DESC  YEAR_ID  TIMEPERIOD_ID  AMOUNT  
0     Farm Price  Cents/Pound     1986              1    70.0  
1     Farm Price  Cents/Pound     1986              2    70.0  
2     Farm Price  Cents/Pound     1986              3    72.0  
3     Farm Price  Cents/Pound     1986              4    74.0  
4     Farm Price  Cents/Pound     1986              5    72.0

In [8]:
cf_filter['GEOGRAPHY_CODE'].unique()

array([9000.])

In [9]:
cf_filter['GEOGRAPHY_DESC'].unique()

array(['United States of America'], dtype=object)

In [10]:
cf_filter['ATTRIBUTE_DESC'].unique()

array(['Farm Price', 'Imports, QTY', 'Processor Price',
       'Farm Sales to Processors', 'Processor Sales, All categories',
       'Processor Inventories'], dtype=object)

In [11]:
cf1=cf_filter[cf_filter['ATTRIBUTE_DESC']=='Farm Price']

In [12]:
cf1.head()

SOURCE_ID COMMODITY_DESC  GEOGRAPHY_CODE            GEOGRAPHY_DESC  \
0        101        Catfish          9000.0  United States of America   
1        101        Catfish          9000.0  United States of America   
2        101        Catfish          9000.0  United States of America   
3        101        Catfish          9000.0  United States of America   
4        101        Catfish          9000.0  United States of America   

  ATTRIBUTE_DESC    UNIT_DESC  YEAR_ID  TIMEPERIOD_ID  AMOUNT  
0     Farm Price  Cents/Pound     1986              1    70.0  
1     Farm Price  Cents/Pound     1986              2    70.0  
2     Farm Price  Cents/Pound     1986              3    72.0  
3     Farm Price  Cents/Pound     1986              4    74.0  
4     Farm Price  Cents/Pound     1986              5    72.0

In [13]:
cf1.shape

(326, 9)

In [17]:
cf_g=cf.groupby(['COMMODITY_DESC','ATTRIBUTE_DESC'])

In [18]:
list_name_g=[]
list_df_g=[]
for n, g in cf_g:
    list_name_g.append(n)
    list_df_g.append(g)

In [29]:
i=10
df=list_df_g[i]
df.shape

(326, 9)

In [30]:
len(list_df_g)

77