## Bài 1
Cho một array 2 chiều.
1. Lấy ra 2 dòng đầu tiên của mảng
2. Sửa giá trị các phần tử cột thứ 0, 2, 4 thành 10

In [31]:
import numpy as np
np.random.seed(0)
A = np.random.randint(10, size=(5,5))
A

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4],
       [7, 6, 8, 8, 1],
       [6, 7, 7, 8, 1],
       [5, 9, 8, 9, 4]])

In [32]:
# task 1
A[0:2]

array([[5, 0, 3, 3, 7],
       [9, 3, 5, 2, 4]])

In [33]:
# task 2
A[:, ::2] =10
A

array([[10,  0, 10,  3, 10],
       [10,  3, 10,  2, 10],
       [10,  6, 10,  8, 10],
       [10,  7, 10,  8, 10],
       [10,  9, 10,  9, 10]])

## Bài 2
Tạo 1 vector ngẫu nhiên chứa 20 phần tử số thập phân, nằm trong khoảng từ -50 đến 50 (dùng `np.random.uniform()`). Hãy làm tròn vector trên về phía 0. Ví dụ: $3.1$ thành $3$, $-5.5$ thành $-5$

In [1]:
import numpy as np
np.random.seed(0)
vector = np.random.uniform(-50, 50, 20)
vector

array([  4.88135039,  21.51893664,  10.27633761,   4.4883183 ,
        -7.63452007,  14.58941131,  -6.24127887,  39.17730008,
        46.36627605, -11.65584812,  29.17250381,   2.88949198,
         6.80445611,  42.55966383, -42.89639418, -41.28707003,
       -47.97816026,  33.26198455,  27.81567509,  37.00121482])

In [4]:
np.copysign(np.floor(np.abs(vector)), vector)

array([  4.,  21.,  10.,   4.,  -7.,  14.,  -6.,  39.,  46., -11.,  29.,
         2.,   6.,  42., -42., -41., -47.,  33.,  27.,  37.])

## Bài 3
Tạo vector A ngẫu nhiên kích thước bằng 50 với các phần tử trong khoảng từ -20 đến 20

1. Tạo vector B chứa trị tuyệt đối của các phần tử trong vector A
2. Chuyển vector B thành ma trận C có kích thước 5x10
3. Tìm phần tử lớn nhất, nhỏ nhất của ma trận C
4. Tính trung bình, trung vị, phương sai của ma trận C, làm tròn 2 chữ số thập phân.
5. Cộng lũy tiến các phần tử trong vector B
6. Chuẩn hóa ma trận C bằng cách lấy mỗi phần tử của C trừ đi trung bình rồi chia độ lệch chuẩn.

In [2]:
import numpy as np

In [8]:
np.random.seed(0)
A = np.random.randint(-20, 20, size=50)
A

array([-20, -17, -17,  19, -11,  -1,   1,  16,   3, -14,   4,   4,  -8,
       -19,  18,  19,   3,   4,  -3,  17,   5,  -7, -12, -11,   0,  -4,
       -15,  -5, -20,  -2,  15,   4,   9,  -1,  -1,  -6,  19,  12, -19,
       -11,  12,  11, -10,   3,  15,  -9,   8,  14, -20, -20])

In [10]:
# task 1
B = np.abs(A)
B

array([20, 17, 17, 19, 11,  1,  1, 16,  3, 14,  4,  4,  8, 19, 18, 19,  3,
        4,  3, 17,  5,  7, 12, 11,  0,  4, 15,  5, 20,  2, 15,  4,  9,  1,
        1,  6, 19, 12, 19, 11, 12, 11, 10,  3, 15,  9,  8, 14, 20, 20])

In [11]:
# task 2
C = B.reshape(5, 10)
C

array([[20, 17, 17, 19, 11,  1,  1, 16,  3, 14],
       [ 4,  4,  8, 19, 18, 19,  3,  4,  3, 17],
       [ 5,  7, 12, 11,  0,  4, 15,  5, 20,  2],
       [15,  4,  9,  1,  1,  6, 19, 12, 19, 11],
       [12, 11, 10,  3, 15,  9,  8, 14, 20, 20]])

In [12]:
# task 3
print(f'Min of C = {C.min()}')
print(f'Max of C = {C.max()}')

Min of C = 0
Max of C = 20


In [17]:
# task 4
print(f'Mean of C = {C.mean():.2f}')
print(f'Variance of C = {C.var():.2f}')
print(f'Median of C = {np.median(C):.2f}')

Mean of C = 10.36
Variance of C = 42.35
Median of C = 11.00


In [28]:
# task 5
np.cumsum(B)

array([ 20,  37,  54,  73,  84,  85,  86, 102, 105, 119, 123, 127, 135,
       154, 172, 191, 194, 198, 201, 218, 223, 230, 242, 253, 253, 257,
       272, 277, 297, 299, 314, 318, 327, 328, 329, 335, 354, 366, 385,
       396, 408, 419, 429, 432, 447, 456, 464, 478, 498, 518], dtype=int32)

In [36]:
# task 6
(C - C.mean()) / C.std()

array([[ 1.48131792,  1.02032686,  1.02032686,  1.32765423,  0.09834476,
        -1.43829208, -1.43829208,  0.86666318, -1.13096472,  0.55933581],
       [-0.97730103, -0.97730103, -0.36264629,  1.32765423,  1.17399055,
         1.32765423, -1.13096472, -0.97730103, -1.13096472,  1.02032686],
       [-0.82363735, -0.51630998,  0.25200844,  0.09834476, -1.59195577,
        -0.97730103,  0.7129995 , -0.82363735,  1.48131792, -1.2846284 ],
       [ 0.7129995 , -0.97730103, -0.20898261, -1.43829208, -1.43829208,
        -0.66997366,  1.32765423,  0.25200844,  1.32765423,  0.09834476],
       [ 0.25200844,  0.09834476, -0.05531893, -1.13096472,  0.7129995 ,
        -0.20898261, -0.36264629,  0.55933581,  1.48131792,  1.48131792]])

## Bài 4
Tạo ra 1 ma trận 8x8 với các phần tử 0 và 1 xen kẽ nhau.

In [35]:
import numpy as np
x = np.zeros((8,8), dtype=int)
x[1::2, ::2] = 1
x[::2, 1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## Bài 5
Tạo một vector ngẫu nhiên có kích thước bằng 10 và thay thế phần tử lớn nhất bằng 0.

In [41]:
import numpy as np
vector = np.random.random(10)
vector[vector.argmax()] = 0
print(vector)

[0.83230823 0.46400219 0.33891652 0.1681727  0.6224092  0.90536451
 0.2568816  0.         0.21029685 0.35491044]
